services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports: 
      - "80:3000"
    tty: true
    volumes:
      - ./app:/app  
      - /app/node_modules
    environment:
      - NODE_ENV=development 
      - WATCHPACK_POLLING=true
    command: ["yarn","dev"]